name: Qt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt update
          sudo apt install -y build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools

      - name: Find and build project
        run: |
          qmake $(find . -name "*.pro")
          make -j$(nproc)
